name: Keep Green

on:
  schedule:
    - cron: '0 12 * * *'  # runs every day at 12:00 PM UTC
  workflow_dispatch:  # allows manual trigger too

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Make a tiny change
      run: |
        echo "$(date)" > last-updated.txt
        
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add last-updated.txt
        git commit -m "Update timestamp"
        git push
